name: Ejecucion de un pipeline basico

env:
  USERNAME: '${{secrets.USERNAME}}'
  PASSWORD: '${{secrets.PASSWORD}}'
run: envsubst
on:
  push:
    branches: 
      - 'master'
  workflow_disparcher:

jobs:
  runs-on: ubuntu-latest
