name: allow-pull-request.yml

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'master'
      - 'feature*'
      - 'hotfix*'

jobs:
  analyze-code:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar la existencia del archivo allow_pull_request.txt
        run: |
          ls -l   # Listar el contenido del directorio de trabajo
          if [ -f "allow_pull_request.txt" ]; then
            echo "El archivo allow_pull_request.txt existe"
          else
            echo "El archivo allow_pull_request.txt no existe"
            ls -l   # Listar el contenido del directorio de trabajo para verificar si el archivo está presente
            exit 1
          fi

      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      - name: Pull Request permitido o no
        run: |
          if [ "${{ env.allow_pull }}" = "true" ]; then
            echo "Permitiendo Pull Request"
          else
            echo "Build fallida. Impidiendo Pull Request"
            exit 1
          fi
