name: ci

on:
  push

jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        - 
          name: Extract branch name
          shell: bash
          run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          id: extract_branch
        -
          name: Check branch master/feature/hotfix
          if: ${{ steps.extract_branch.outputs.branch != 'master' && !(contains( steps.extract_branch.outputs.branch , 'feature' )) && !(contains( steps.extract_branch.outputs.branch , 'hotfix')) }}
          run: exit -1
        -
          name: Pruebas de SAST
          run: echo 'Ejecución de pruebas de SAST'
        -
          name: Creación de credenciales
          uses: "DamianReeves/write-file-action@master"
          with:
            path: ./.config/credentials.ini
            write-mode: overwrite
            contents: |
              USERNAME = ${{ secrets.USERNAME }} , PASSWORD = ${{ secrets.PASSWORD }}
        -
          uses: actions/checkout@v3
        -
          name: Build docker image
          working-directory: .
          run: docker build --file Dockerfile -t devops_ws .