name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"
        
      - name: Set up environment variables
        run: |
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          
      - name: Create INI file
        run: |
          echo "[Credentials]" > credentials.ini
          echo "username=$USERNAME" >> credentials.ini
          echo "password=$PASSWORD" >> credentials.ini  

      - name: Print current directory file list
        run: ls -al

      - name: Build docker image
        run: docker build -t devops_ws . --tag devops_ws_$(date +%s)
        working-directory: . 