name: DevOps Pipeline

on:
  push:
    branches:
      - master
      - 'feature*'
      - 'hotfix*'  # Ejecutar cuando se realiza un push a la rama master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"
      
      - uses: actions/checkout@v4

      - name: Create credentials file
        run: |
          cat > credentials.ini <<EOF
          [credentials]
          username = ${{ secrets.USERNAME }}
          password = ${{ secrets.PASSWORD }}
          EOF
  
      - name: Build docker image
        run: docker build -t devops_ws . --tag devops_ws_$(date +%s)
