name: CI Pipeline for Ines

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Pruebas de SAST (mocked)
      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"
      
      # Step 2: Crear archivo de credenciales
      - name: Crear archivo de credenciales
        run: |
          echo "[credentials]" > credentials.ini
          echo "username=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini
      
      # Step 3: Listar archivos en la raíz para verificar que Dockerfile está presente
      - name: Listar archivos en la raíz
        run: ls -l
      
      # Step 4: Construcción del container Docker desde el directorio raíz
      - name: Build docker image
        working-directory: .  # Asegúrate de que está en la raíz
        run: docker build -t devops_ws . --tag devops_ws:$(date +%s)
